version: "3"

services:
  web:
    container_name: heroesapi
    restart: always
    build: .
    ports:
      - "8080:3000"
    links:
      - mongo
    volumes: 
      - .:/usr/src/app
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27018:27017"
